version: '3'
services:
  zelos_react_mongo:
    container_name: zelos_react_mongo
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - db:/data/db

  zelos_react_backend:
    container_name: zelos_react_backend
    image: zelos_react_backend:latest
    environment:
      SECRET: "d7037517b12d4450a9cf37e30f834c4e"
      NODE_ENV: production
      DATABASE_PORT: 27017
    restart: always
    volumes:
      - 'uploads:/home/node/uploads'

  zelos_react_nginx:
    container_name: zelos_react_nginx
    image: zelos_react_nginx:latest
    restart: always
    volumes:
      - 'uploads:/var/www/zelos_uploads'
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    links:
      - zelos_react_backend

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - zelos_react_nginx
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt

volumes:
  certbot-etc:
  certbot-www:
  uploads:
  db:
